name: v_downloader
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  filex: ^0.2.2
  path: ^1.6.4
  youtube_player_flutter: ^6.1.0+4
  http: ^0.12.0+2
  youtube_extractor: ^1.0.4
  folder_picker: ^0.3.0
  percent_indicator: "^2.1.1"
  flutter_downloader: ^1.3.3
  # workmanager: ^0.1.3
  permission_handler: ^3.2.2
  sqflite: ^1.1.7+1
  shared_preferences: ^0.5.3+4
  scoped_model: ^1.0.1
  random_string: ^1.1.0
  chewie: ^0.9.8+1
  video_player: ^0.10.2+5
  flute_music_player: ^0.0.6
  rxdart: ^0.22.0
  sliding_up_panel: ^0.3.4
  audioplayers: ^0.15.0
  url_launcher: ^3.0.2
  path_provider_ex: ^1.0.0
  connectivity: ^0.4.5+3
  # firebase_admob: ^0.9.3+1
  firebase_admob: ^0.9.0+1







permission:
  git:
    url: https://github.com/devadrianapostol/permission

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  youtube_api: ^0.7.2
  cached_network_image: 2.0.0-rc

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
   - assets/icon/logo.png
   - assets/placeholder.png
   
